
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import Footer from "../components/Footer";
import Header from "../components/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import Link from "next/link";
// import GlobalContextProvider from './context/store'

import { ToastContainer } from "react-toastify";
// import Header from "@/components/Header";
// import UserProvider from "@/context/userProvider";
import Script from 'next/script'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <GlobalContextProvider> */}
          <Header />
          <div className="mt-0"> {children}</div>
          <Footer />
        {/* </GlobalContextProvider */}
      </body>
    </html>
  );
}
